FaceRecognition/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView, 
    PasswordResetCompleteView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('facial_app.api.urls')),
    path('', include('facial_app.urls')),
    path('user/api/', include('user_app.api.urls')),
    path('user/', include('user_app.urls')),
    #Password Related Views
    path('api/password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
    # path('password_reset/', PasswordResetView.as_view(), name='password_reset_form'),
    # path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facial_app/urls.py
from django.urls import path
from django.conf import settings
from facial_app import views
from django.views.generic import TemplateView
from django.conf.urls.static import static

app_name = 'facial'
urlpatterns = [
    path('', TemplateView.as_view(template_name='landingPage.html'), name='home'),
    path('login/admin/', TemplateView.as_view(template_name='login_admin.html'), name='login_admin'),
    path('login/student/', TemplateView.as_view(template_name='login_student.html'), name='login_student'),
    path('login/lecturer/', TemplateView.as_view(template_name='login_lecturer.html'), name='login_lecturer'),
    path('signup/student/', TemplateView.as_view(template_name='signup_student.html'), name='signup_student'),
    path('signup/lecturer/', TemplateView.as_view(template_name='signup_lecturer.html'), name='signup_lecturer'),
    path('password_reset/', TemplateView.as_view(template_name='passwordreset/password_reset_form.html'), name='password_reset'),
    path('password_confirm/', views.PasswordRestConfirm.as_view(), name='password_confirm'),
    path('create/attendance/', views.DashBoardView.as_view(), name='create_attendance'),
    path('attendance/', views.AttendanceListView.as_view(), name='view_attendance'),
    path('take/attendance/', views.TakeAttendanceCreateView.as_view(), name='take_attendance'),
    path('profile/student/', views.StudentProfileView.as_view(), name='profile_student'),
    path('profile/lecturer/', views.LecturerProfileView.as_view(), name='profile_lecturer'),
    path('feedback/', views.FeedbackCreateView.as_view(), name='feedback'),
    path('profile/student/edit/', views.StudentProfileEditView.as_view(), name='profile_student_edit'),
    path('profile/lecturer/edit/', views.LecturerProfileEditView.as_view(), name='profile_lecturer_edit'),
]

user_app/urls.py
from django.urls import path
from user_app.api import views

app_name = 'user'
urlpatterns = [
    
]

facial_app/models.py
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.db.models.deletion import CASCADE
from facial_app.api.manager import UserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from PIL import Image
import datetime

GENDER_CHOICE = (('Male','Male'),('Female','Female'))
LEVEL_CHOICE = (('100','100'),('200','200'),('300','300'),('400','400'),)
SEMESTER_CHOICE = (('First','First'),('Second','Second'))
DEPARTMENT  = (
        ('Computer Science','Computer Science'),
        ('Mathematics', 'Mathematics'),
        ('Statistics','Statistics'),
        ('Physics', 'Physics'),
        ('Chemistry','Chemistry'),
        ('Biology','Biology'),
        ('Political Science','Political Science'),
        ('Economics','Economics'),
        ('Mass Communication','Mass Communication'),
        ('History','History'),
        ('English','English'),
    )
FACULTY = (('Science','Science'),('Social Science','Social Science'),('Arts','Arts'))

def upload_to(instance, filename):
    return 'profile_pics/{filename}'.format(filename=filename)

class User(AbstractUser):
    """CustomUser model."""
    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },)
    email = models.EmailField(_('email address'), unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]
    objects = UserManager()
    contact = models.CharField(validators = [RegexValidator(regex = r"^\+?1?\d{8,15}$")], max_length = 16)
    gender = models.CharField(choices=GENDER_CHOICE, max_length=34, default='Male')    
    is_student = models.BooleanField(default=False)
    is_lecturer = models.BooleanField(default=False)
    signup_confirmation = models.BooleanField(default=False) 
    avatar = models.ImageField(_('Image'), upload_to=upload_to, default='default.png')

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super().save()
        try:
            image = Image.open(self.avatar.path)
            if image.height > 300 or image.width > 300:
                image.thumbnail((150,150))
                image.save(self.avatar.path)   
        except:
            print("******Error in Processing images*******")
            return        
    
    @property
    def get_photo_url(self):
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        else:
            return "/static/default.png"

    def __str__(self):
        return f'{self.email}'


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE, related_name='student')
    matric_no = models.CharField(max_length=15)
    semester = models.CharField(choices=SEMESTER_CHOICE, max_length=10, default='First')
    level = models.CharField(choices=LEVEL_CHOICE, max_length=5, default='100')
    dob = models.DateField(max_length=23)
    department = models.CharField(choices=DEPARTMENT, max_length=30, default='Computer Science')
    
    def __str__(self):
        return f'{self.matric_no}'
    

class Lecturer(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE, related_name='lecturer')
    department = models.CharField(choices=DEPARTMENT, max_length=30, default='Computer Science')
    faculty = models.CharField(choices=FACULTY, max_length=30, default='Science')

    def __str__(self):
        return f'{self.user.get_full_name()} | {self.department}'


class Attendance(models.Model):
    lecturer = models.ForeignKey(User, on_delete=CASCADE, related_name='user_lecturer')
    student = models.ForeignKey(User, on_delete=CASCADE)
    matric_no = models.CharField(max_length=200, null=True, blank=True)
    department = models.CharField(max_length=200, null=True, blank=True)
    level = models.CharField(max_length=200, null=True, blank=True)
    course = models.CharField(null=True, max_length=6)
    date = models.DateField(auto_now_add = True, null = True)
    time = models.TimeField(auto_now_add=True, null = True)
    present = models.CharField(default="Absent", max_length=10)

    def __str__(self):
        return f"{self.student} | {self.department}"


class CreateAttendance(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    title = models.CharField(max_length=100)
    level = models.CharField(choices=LEVEL_CHOICE, max_length=5, default='100')
    department = models.CharField(choices=DEPARTMENT, max_length=30, default='Computer Science')
    course = models.CharField(max_length=10)
    duration = models.PositiveIntegerField(default=2, validators=[MinValueValidator(2), MaxValueValidator(10)])
    created = models.DateTimeField(null=True)
    code = models.CharField(max_length=6)

    def __str__(self):
        return f"{self.user} | {self.title}"


class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    subject = models.CharField(max_length=40)
    message = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.email} | {self.subject}'

templates/activate.html
{% load i18n %}
{% autoescape off %}
Hi {{user.first_name}}!

Please click the link below to activate your account.

http://127.0.0.1:8000{% url 'activate' uidb64=uid token=token%}

You can also copy and paste it on your browser.

{% trans "Thanks for signing up!" %}

Sincerely,
The FaceAttendanceApp Team
{% endautoescape %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="Facial Attendance Application" name="description">
  <meta content="Facial Recognition Student Attendance" name="keywords">

  <title>{% block page_title %}Attendance{% endblock %}</title>
  
  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
  
  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% if user.is_lecturer %}{% url 'facial:create_attendance' %}{% elif user.is_student %}{% url 'facial:take_attendance' %}{% else %}{% url 'facial:home' %}{% endif %}" class="logo d-flex align-items-center">
        <img src="{% static 'img/logo.png' %}" alt="logo">
        <span>Attendance</span>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li class="dropdown"><a><span>Login</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="{% url 'facial:login_student' %}">Student</a></li>
              <li><a href="{% url 'facial:login_lecturer' %}">Lecturer</a></li>
              <!-- <li><a href="{% url 'facial:login_admin' %}">Admin</a></li> -->
            </ul>
          </li>
          <li class="dropdown"><a class="getstartednow"><span>Signup</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="{% url 'facial:signup_student' %}">Student</a></li>
              <li><a href="{% url 'facial:signup_lecturer' %}">Lecturer</a></li>
            </ul>
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
  
  <!-- Spinner Start -->
  <div id="ajax-loader" class="text-center" style="background-color: rgba(255,255,255,0.8); position: absolute; padding-top: 50vh; z-index: +100 !important;
  width: 100%; height:100%; visibility: hidden;">
    <div class="spinner-border text-primary" role="status">
      <span class="sr-only"></span>
    </div>
  </div>
  <!-- Spinner End -->
  
  {% block content %}{% endblock content %}

  <script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
  <!-- Vendor JS Files -->
  <script src="{% static 'assets/bootstrap/js/bootstrap.bundle.js' %}"></script>
  <script src="{% static 'assets/aos/aos.js' %}"></script>
  <script src="{% static 'assets/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'assets/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/glightbox/js/glightbox.min.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/jquery/jquery.min.js' %} "></script>
  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>
  <script src="{% static 'js/api.js' %}"></script>
  

</body>

</html>

templates/feedback.html
{% extends 'dashboard.html' %}
{% load static %}

{% block page_title %}Feedback{% endblock %}

{% block SideBar %}
<!-- SideBar -->
		<nav id="sidebar" class="sidebar js-sidebar">
			<div class="sidebar-content js-simplebar">				
				<a class="sidebar-brand" href="{% url 'facial:home' %}">
          			<span class="align-middle">Welcome {{ request.user.first_name }}</span>
        		</a>
				<ul class="sidebar-nav">
					<li class="sidebar-header">Menu</li>
					{% if request.user.is_lecturer %}
						<li class="sidebar-item">
							<a class="sidebar-link" href="{% url 'facial:create_attendance' %}">
								<i class="align-middle" data-feather="file-plus"></i> <span class="align-middle">Create Attendance</span>
							</a>
						</li>
						<li class="sidebar-item">
							<a class="sidebar-link" href="{% url 'facial:profile_lecturer' %}">					
								<i class="align-middle" data-feather="user"></i> <span class="align-middle">Profile</span>
							</a>
						</li>
					{% endif %}
					{% if request.user.is_lecturer %}					
						<li class="sidebar-item">
							<a class="sidebar-link" href="{% url 'facial:view_attendance' %}">
								<i class="align-middle" data-feather="file-text"></i> <span class="align-middle">Attendance Sheet</span>
							</a>
						</li>
					{% endif %}					
					{% if request.user.is_student %}
						<li class="sidebar-item">
							<a class="sidebar-link" href="{% url 'facial:take_attendance' %}">
								<i class="align-middle" data-feather="plus-square"></i> <span class="align-middle">Take Attendance</span>
							</a>
						</li>
						<li class="sidebar-item">
							<a class="sidebar-link" href="{% url 'facial:profile_student' %}">					
								<i class="align-middle" data-feather="user"></i> <span class="align-middle">Profile</span>
							</a>
						</li>
					{% endif %}					
					<li class="sidebar-item active">
						<a class="sidebar-link" href="{% url 'facial:feedback' %}">
              				<i class="align-middle" data-feather="help-circle"></i> <span class="align-middle">Feedback</span>
            			</a>
					</li>
					<li class="sidebar-item" id="logout-btn">
						<a class="sidebar-link">
              				<i class="align-middle" data-feather="log-out"></i> <span class="align-middle">Logout</span>
            			</a>
					</li>
				</ul>
			</div>
		</nav>
		<!-- End SideBar -->
{% endblock SideBar %}

{% block dashboard %}
<div class="card">
    <div class="card-body">
        <form method="POST" class="feedback-form" id="feedback-form">
            {% csrf_token %}
            <h6 class="d-flex align-items-center mb-3"><strong>Feedback</strong></h6>
            <!-- Display Messsage -->
            <div class="col-lg-8 mt-5 mt-lg-0">
            {% if messages %}
                {% for message in messages %}
                <div class="container-fluid p-0">
                    <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    {{ message }}
                    </div>
                </div>
                {% endfor %}
            {% endif %}
            <!-- Display Alert Message -->
            <div class="container-fluid p-0">
                <div id="alert" role="alert">
                    <p></p>
                </div>
            </div>
            <!-- End Alert Message -->
            <div class="row mb-3">
                <div class="col">
                    <h6 class="mb-2">Subject</h6>
                    <input type="text" class="form-control" id="subject" name="subject" placeholder="Title" required/>
                </div>                
            </div>
            <div class="row">
                <div class="col">
                    <h6 class="mb-2">Message</h6>
                    <textarea class="form-control" rows="12" id="message" name="message" placeholder="Message" required></textarea>
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-2"><i data-feather="send"></i> Send</button>
        </form>        
    </div>
</div>
{% endblock dashboard %}

templates/profile_lecturer_edit.html
{% extends 'dashboard.html' %}
{% load static %}

{% block page_title %}Lecturer Profile Edit{% endblock %}

{% block SideBar %}
<!-- SideBar -->
		<nav id="sidebar" class="sidebar js-sidebar">
			<div class="sidebar-content js-simplebar">				
				<a class="sidebar-brand" href="{% url 'facial:home' %}">
          			<span class="align-middle">Welcome {{ request.user.first_name }}</span>
        		</a>
				<ul class="sidebar-nav">
					<li class="sidebar-header">Menu</li>
					{% if request.user.is_lecturer %}
						<li class="sidebar-item">
							<a class="sidebar-link" href="{% url 'facial:create_attendance' %}">
								<i class="align-middle" data-feather="file-plus"></i> <span class="align-middle">Create Attendance</span>
							</a>
						</li>
						<li class="sidebar-item active">
							<a class="sidebar-link" href="{% url 'facial:profile_lecturer' %}">					
								<i class="align-middle" data-feather="user"></i> <span class="align-middle">Profile</span>
							</a>
						</li>
					{% endif %}
					{% if request.user.is_lecturer %}					
						<li class="sidebar-item">
							<a class="sidebar-link" href="{% url 'facial:view_attendance' %}">
								<i class="align-middle" data-feather="file-text"></i> <span class="align-middle">Attendance Sheet</span>
							</a>
						</li>
					{% endif %}					
					{% if request.user.is_student %}
						<li class="sidebar-item">
							<a class="sidebar-link" href="{% url 'facial:take_attendance' %}">
								<i class="align-middle" data-feather="plus-square"></i> <span class="align-middle">Take Attendance</span>
							</a>
						</li>
						<li class="sidebar-item">
							<a class="sidebar-link" href="{% url 'facial:profile_student' %}">					
								<i class="align-middle" data-feather="user"></i> <span class="align-middle">Profile</span>
							</a>
						</li>
					{% endif %}					
					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'facial:feedback' %}">
              				<i class="align-middle" data-feather="help-circle"></i> <span class="align-middle">Feedback</span>
            			</a>
					</li>
					<li class="sidebar-item" id="logout-btn">
						<a class="sidebar-link">
              				<i class="align-middle" data-feather="log-out"></i> <span class="align-middle">Logout</span>
            			</a>
					</li>
				</ul>
			</div>
		</nav>
		<!-- End SideBar -->
{% endblock SideBar %}

{% block dashboard %}
<div class="row">
  <div class="container">
		<div class="main-body">
			<div class="row">
				<div class="col-lg-4">
					<div class="card">
						<div class="card-body">
							<div class="d-flex flex-column align-items-center text-center">								
								<img src="{% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'default.png' %} {% endif %}" alt="Lecturer Picture" class="rounded-circle p-1 bg-primary" width="150" height="150">						
								<div class="mt-3">
									<h4><b>{{ user.get_full_name }}</b></h4>
									<p class="text-secondary mb-1">Lecturer | {{ user.lecturer.department }}</p>
									<p class="text-muted font-size-sm">Faculty of {{ user.lecturer.faculty }}</p>
									<div class="container d-flex justify-content-center">										
										<!-- Upload Avatar -->
										<form method="POST" class="avatar-upload-form" id="avatar-upload-form" accept="image/*" enctype="multipart/form-data">
											{% csrf_token %}
											<div class="form-group align-content-center">
												<!-- Display Alert Message -->
												<div class="container d-flex justify-content-center p-0">
													<div class="row">
														<div class="col">
															<div id="avatar-alert" role="alert">
															</div> 
														</div>									 
													</div>								
												</div>
												<!-- End Alert Message -->
												<label for="avatar"><strong>Choose an image for your Avatar</strong></label>
												<input type="file" class="form-control-file m-1" id="id_avatar" style="padding-left: 100px;"/>
											</div>
											<button type="submit" class="btn btn-primary mt-2">Upload</button>
										</form>
										<!-- End Upload Avatar -->
									</div>									
								</div>
							</div>
							<hr class="my-4">
							<ul class="list-group list-group-flush">
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><i data-feather="mail"></i> Email</h6>
									<span class="text-secondary">{{ user.email }}</span>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><i data-feather="phone"></i> Phone</h6>
									<span class="text-secondary">{{ user.contact }}</span>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-8">
					<!-- Lecture Profile Edit -->
					<form id="lecturer-profile-update">
						{% csrf_token %}
						<div class="card">
							<h4 class="m-3">Update Profile</h4>
							<div class="card-body">
								<!-- Display Alert Message -->
								<div class="container-fluid p-0">
									<div class="row">
										<div class="col-md-12">
											<div id="alert" role="alert">
											</div> 
										</div>									 
									</div>								
								</div>
								<!-- End Alert Message -->
								<div class="row mb-3 mt-2">
									<div class="col-sm-3">
										<h6 class="mb-0">First Name</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										<input type="text" class="form-control" placeholder="First Name" id="first_name" name="first_name" value={{ user.first_name }} required/>
									</div>
								</div>
								<div class="row mb-3">
									<div class="col-sm-3">
										<h6 class="mb-0">Last Name</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										<input type="text" class="form-control" placeholder="Last Name" id="last_name" name="last_name" value={{ user.last_name }} required/>
									</div>
								</div>
								<div class="row mb-3">
									<div class="col-sm-3">
										<h6 class="mb-0">Gender</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										<select class="form-select mb-3" value={{ user.gender }} id="gender" name="gender" >
											{% for gen in Gender %}
												<option value={{ gen }} {% if gen == user.gender %}selected{% endif %}>{{ gen }}</option>
											{% endfor %}
										</select>
									</div>
								</div>
								<div class="row mb-3">
									<div class="col-sm-3">
										<h6 class="mb-0">Mobile</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										<input type="text" class="form-control" placeholder="(+234) 380-4539"  id="contact" name="contact" value={{ user.contact }} required/>
									</div>
								</div>
								<div class="row mb-3">
									<div class="col-sm-3">
										<h6 class="mb-0">Department</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										<select class="form-select mb-3" id="department" name="department" >
											{% for depts in Departments %}
												<option value={{ depts }} {% if depts == user.lecturer.department %}selected{% endif %}>{{ depts }}</option>
											{% endfor %}
										</select>
									</div>
								</div>
								<div class="row mb-3">
									<div class="col-sm-3">
										<h6 class="mb-0">Faculty</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										<select class="form-select mb-3" id="faculty" name="faculty" >
											{% for fa in Faculties %}
												<option value={{ fa }} {% if fa == user.lecturer.faculty %}selected{% endif %}>{{ fa }}</option>
											{% endfor %}
										</select>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-3"></div>
									<div class="col-sm-9 text-secondary">
										<input type="submit" class="btn btn-primary px-4" value="Save Changes">
									</div>
								</div>
							</div>
						</div>	
					</form>
					<!-- Lecturer Change Password -->
					<form id="change-password-update">
						{% csrf_token %}
						<div class="card">
							<h4 class="m-3">Change Password</h4>							 
							<div class="card-body">
								<!-- Display Alert Message -->
								<div class="container-fluid p-0">
									<div class="row">
										<div class="col-md-12">
											<div id="alert_change_psw" role="alert">
											</div> 
										</div>									 
									</div>								
								</div>
								<!-- End Alert Message -->
								<div class="row mb-3 mt-2">
									<div class="col-sm-3">
										<h6 class="mb-0">Old Password</h6>
									</div>
									<div class="col-sm-9 text-secondary">										
										<input type="password" class="form-control" id="old_password" name="old_password" placeholder="Old Password" required/>
										<i onclick="changePasswordToggled('old_password','togglePassword')" class="far fa-eye" id="togglePassword" style="float: right; cursor: pointer; margin-top: -24px; margin-right: 15px;"></i>		
									</div>
								</div>
								<div class="row mb-3">
									<div class="col-sm-3">
										<h6 class="mb-0">New Password</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										<input type="password" class="form-control" id="new_password" name="new_password" placeholder="New Password" required/>
										<i onclick="changePasswordToggled('new_password','togglePassword1')" class="far fa-eye" id="togglePassword1" style="float: right; cursor: pointer; margin-top: -24px; margin-right: 15px;"></i>
									</div>
								</div>
								<div class="row mb-3">
									<div class="col-sm-3">
										<h6 class="mb-0">Confirm Old Password</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										<input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Confirm New Password" required/>
										<i onclick="changePasswordToggled('confirm_password','togglePassword2')" class="far fa-eye" id="togglePassword2" style="float: right; cursor: pointer; margin-top: -24px; margin-right: 15px;"></i>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-3"></div>
									<div class="col-sm-9 text-secondary">
										<input type="submit" class="btn btn-primary px-4" value="Change Password">
									</div>
								</div>
							</div>
						</div>	
					</form>	
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock dashboard %}